# Generated by Django 2.1 on 2020-03-17 09:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('fieldOfStudy', models.CharField(max_length=200)),
                ('startYear', models.IntegerField(blank=True, null=True)),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('certificate', models.TextField()),
                ('additionalNotes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('profilePhoto', models.ImageField(blank=True, default='https://userpic.codeforces.com/no-avatar.jpg', null=True, upload_to='profilePhoto/%Y/%m/%D/')),
                ('summary', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.School'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blink.User'),
        ),
    ]
