# Generated by Django 2.1 on 2020-03-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='legitimate',
            field=models.BooleanField(default=True),
        ),
    ]
