# Generated by Django 2.1 on 2020-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0002_education_legitimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
